version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: heart_disease
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: heart_disease_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:password@db:5432/heart_disease
    ports:
      - "5000:5000"
    volumes:
      - .:/app

volumes:
  pg_data:
