apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-disease-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: heart-disease
  template:
    metadata:
      labels:
        app: heart-disease
    spec:
      containers:
      - name: heart-disease-api
        image: your-dockerhub-username/heart-disease-api:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: heart-disease-service
spec:
  selector:
    app: heart-disease
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
